version: "3.9"
services:
  app:
    build: .
    ports: 
      - 5001:5000
    depends_on:
      - sql-server-db
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqldata:/var/opt/mssql
    user: root
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "RF1qaz2WSX!"
      ACCEPT_EULA: "Y"
volumes:
  sqldata:
